global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'dks'
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['dks:8443']
    tls_config:
      insecure_skip_verify: true
  - job_name: 'ide'
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['172.17.0.1:8443']
    tls_config:
      insecure_skip_verify: true
